### PR TITLE
Hotfix/icons

### PR DESCRIPTION
**Pull request by frontendschlampe**
see https://github.com/contao/core-bundle/issues/693

### CODE REVIEW

**Comment by leofeyer** [comment]
Why did you not base the PNG icon on the existing TIFF icon?

**Comment by frontendschlampe** [comment]
Because I think, that nobody can see the graphic elements behind the SVG writing, but if you want, I will add it.

**Comment by leofeyer** [comment]
I'm just suggesting consistency. Either all image icons have a graphic element or none. You know what I mean?

**Comment by frontendschlampe** [comment]
Yes, I know, what you mean, but it was not consistent till now.

```bmp``` -> just graphic element
```gif``` -> just graphic element
```jpg``` -> just graphic element
```tiff``` -> graphic element with "TIFF"-writing
```svg``` -> no graphic element and no writing
```png``` -> just "PNG"-writing

So if we want to do it consistent, we should do it for every image icon. So we have two possibilities:

1. for every icon a graphic element and no writing of file format
2. for every icon no graphic element but a writing of file format

I think, that possibility 2 will identify the icons clearly and it will be more consistent to all other icons.

So what do you think?

**Comment by leofeyer** [comment]
Wow, thank you a lot for creating/changing 115 icons!

**Pull request merged**
